name: 'Blazium Setup'

description: 'Setup Blazium Engine for use with macOS, Windows, and Linux CI/CD runners.'

author: 'blazium-engine'
branding:
  icon: 'hard-drive'
  color: 'white'
inputs:
  version:
    description: 'Blazium Engine version: e.g., 0.1.184, 0.1.188, etc. Must include major, minor, and patch.'
    required: true
  bin-path:
    description: 'Path for binaries to be installed to, relative to the current working directory of the action. This is the path that will be added to the system path.'
    default: 'bin'
  arch:
    description: 'Specify the architecture (e.g., x86_64, arm64, arm32, 32bit, 64bit).'
    default: ''
  platform:
    description: 'Specify the platform (e.g., linux, windows, macos).'
    default: ''
  download_editor:
    description: 'Download Blazium CLI Editor'
    default: 'true'
  download_template:
    description: 'Download Blazium CLI Template'
    default: 'false'
  download_mono:
    description: 'Download Blazium Mono Version'
    default: 'false'
  use-cache:
    description: 'Use cache'
    default: 'true'
  
runs:
  using: composite
  steps:
    - uses: blazium-engine/setup-blazium-cli@master
      name: 🤖 Setup Blazium CLI
      with:
        version: 0.0.14

    - name: Cache Blazium Editor
      if: ${{ inputs.download_editor == 'true' || inputs.use_cache == 'true' }}
      id: cache-editor
      uses: actions/cache@v3
      with:
        path: ${{ inputs.bin-path }}/editor
        key: ${{ runner.os }}-blazium-editor-${{ inputs.version }}-${{ inputs.platform }}-${{ inputs.arch }}

    - name: Blazium Editor Download
      if: ${{ inputs.download_editor == 'true'}}
      shell: bash
      run: |
        echo "Runner os is ${{ runner.os }}"
        if [ "${{ runner.os }}" == "Linux" ]; then
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=linux
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=x86_64
          else
            arch=${{ inputs.arch }}
          fi
        elif [ "${{ runner.os }}" == "Windows" ]; then
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=windows
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=64bit
          else
            arch=${{ inputs.arch }}
          fi
        else
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=macos
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=macos
          else
            arch=${{ inputs.arch }}
          fi
        fi
        if [ "${{ inputs.download_mono }}" == "true" ]; then
          mono=" --mono"
        else
          mono=""
        fi
        if [ "${{ steps.cache-editor.outputs.cache-hit }}" != "true" ]; then
          echo "Using platform $platform and arch $arch and mono $mono"
          mkdir -p ${{ inputs.bin-path }}/editor
          ${{ env.BLAZIUM_CLI }} --get-version ${{ inputs.version }} --arch $arch --download --editor --platform $platform$mono ${{ inputs.bin-path }}/editor
          
          echo "Unzipping editor"
          # Unzip 1st time
          file=$(ls ${{ inputs.bin-path }}/editor)
          ls -lah ${{ inputs.bin-path }}/editor
          unzip ${{ inputs.bin-path }}/editor/$file -d ${{ inputs.bin-path }}/editor
          rm ${{ inputs.bin-path }}/editor/$file

          if [ "$platform" == "macos" ]; then
            # Unzip 2nd time
            file=$(ls ${{ inputs.bin-path }}//editor)
            unzip ${{ inputs.bin-path }}/editor/$file -d ${{ inputs.bin-path }}/editor
            rm ${{ inputs.bin-path }}/editor/$file
          fi
          # Move file
          if [ "$platform" == "linux" ]; then
            file=$(ls ${{ inputs.bin-path }}/editor)
            chmod +x ${{ inputs.bin-path }}/editor/$file
            # Rename it to Blazium
            mv ${{ inputs.bin-path }}/editor/$file ${{ inputs.bin-path }}/editor/Blazium
          elif [ "$platform" == "windows" ]; then
            # Find an executable that is NOT a .console.exe
            file=$(find "${{ inputs.bin-path }}/editor" -type f -name '*.exe' ! -name '*.console.exe' | head -n 1)
            # Rename to Blazium.exe
            mv $file ${{ inputs.bin-path }}/editor/Blazium.exe
            ls -lah ${{ inputs.bin-path }}/editor
          fi

        else
          echo "Using cached platform $platform and arch $arch and mono $mono"
          ls ${{ inputs.bin-path }}/editor
        fi
        
        # Add Blazium to PATH
        echo "${{ inputs.bin-path }}/editor" >> $GITHUB_PATH

        # Export Blazium Editor ENV
        if [ "$platform" == "macos" ]; then
          echo "${{ inputs.bin-path }}/editor/Blazium.app/Contents/MacOS" >> $GITHUB_PATH
          echo "BLAZIUM_EDITOR=${{ inputs.bin-path }}/editor/Blazium.app/Contents/MacOS/Blazium" >> $GITHUB_ENV
        elif [ "$platform" == "linux" ]; then
          echo "BLAZIUM_EDITOR=${{ inputs.bin-path }}/editor/Blazium" >> $GITHUB_ENV
        else
          echo "BLAZIUM_EDITOR=${{ inputs.bin-path }}/editor/Blazium.exe" >> $GITHUB_ENV
        fi

    - name: Verify Blazium Editor Installation
      shell: bash
      if: ${{ inputs.download_editor == 'true' }}
      run: |
        ${{ env.BLAZIUM_EDITOR }} --version

    - name: Cache Blazium Template
      if: ${{ inputs.download_template == 'true' && inputs.use_cache == 'true' }}
      id: cache-template
      uses: actions/cache@v3
      with:
        path: ${{ inputs.bin-path }}/templates
        key: ${{ runner.os }}-blazium-template-${{ inputs.version }}-${{ inputs.platform }}-${{ inputs.arch }}
            
    - name: Blazium Template
      if: ${{ inputs.download_template == 'true' }}
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=linux
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=x86_64
          else
            arch=${{ inputs.arch }}
          fi
        elif [ "${{ runner.os }}" == "Windows" ]; then
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=windows
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=x86_64
          else
            arch=${{ inputs.arch }}
          fi
        else
          if [ "${{ inputs.platform }}" == "" ]; then
            platform=macos
          else
            platform=${{ inputs.platform }}
          fi
          if [ "${{ inputs.arch }}" == "" ]; then
            arch=macos
          else
            arch=${{ inputs.arch }}
          fi
        fi
        if [ "${{ inputs.download_mono }}" == "true" ]; then
          mono=" --mono"
        else
          mono=""
        fi
        echo "Using platform $platform and arch $arch and mono $mono"

        mkdir -p ${{ inputs.bin-path }}/templates
        if [ "${{ steps.cache-template.outputs.cache-hit }}" != "true" ]; then
          ${{ env.BLAZIUM_CLI }} --get-version ${{ inputs.version }} --arch $arch --download --template --platform $platform$mono ${{ inputs.bin-path }}/templates
        else
          echo "Using cached template"
          ls ${{ inputs.bin-path }}/templates
        fi
        file=$(ls ${{ inputs.bin-path }}/templates)
        # Replace - with .
        version_dot=$(echo "${{ inputs.version }}" | sed 's/-/./')
        
        echo "Unzipping template"
        if [ "$platform" == "macos" ]; then
          mkdir -v -p "/Users/runner/Library/Application Support/Blazium/export_templates"
          unzip ${{ inputs.bin-path }}/templates/$file -d "/Users/runner/Library/Application Support/Blazium/export_templates/$version_dot"
          ls "/Users/runner/Library/Application Support/Blazium/export_templates/$version_dot"
          echo "BLAZIUM_TEMPLATE=\"/Users/runner/Library/Application Support/Blazium/export_templates/$version_dot\"" >> $GITHUB_ENV
        elif [ "$platform" == "linux" ]; then
          mkdir -v -p $HOME/.local/share/blazium/export_templates
          unzip ${{ inputs.bin-path }}/templates/$file -d $HOME/.local/share/blazium/export_templates/$version_dot
          ls $HOME/.local/share/blazium/export_templates/$version_dot
          echo "BLAZIUM_TEMPLATE=$HOME/.local/share/blazium/export_templates/$version_dot" >> $GITHUB_ENV
        else
          mkdir -v -p "$HOME/AppData/Roaming/Blazium/export_templates"
          unzip ${{ inputs.bin-path }}/templates/$file -d "$HOME/AppData/Roaming/Blazium/export_templates/$version_dot"
          ls "$HOME/AppData/Roaming/Blazium/export_templates/$version_dot"
          echo "BLAZIUM_TEMPLATE=\"$HOME/AppData/Roaming/Blazium/export_templates/$version_dot\"" >> $GITHUB_ENV
        fi

