name: Test Download

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [0.4.39-release, 0.4.10-nightly, latest, latest-nightly, latest-release, latest-0, latest-0.4, latest-0.3, latest-nightly, latest-release, latest-nightly-0, latest-nightly-0.3, latest-release-0, latest-release-0.4]
        os: [{
          name: ubuntu-latest,
          platform: linux
          }, {
          name: macos-latest,
          platform: macos
          }, { 
          name: windows-latest,
          platform: windows
          }]
    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v4

      - uses: blazium-engine/setup-blazium@master
        name: 🤖 Setup Blazium
        with:
          version: ${{ matrix.version }}
          download_template: true
          platform: ${{ matrix.os.platform }}

      - name: 🔬 Verify Setup
        run: |
          Blazium --version
      
      - name: 🔬 Verify Blazium Template Installation
        shell: bash
        run: |
          # Check that the template is installed
          ls ${{ env.BLAZIUM_TEMPLATE }}
          # Check that the template is not empty
          if [ -z "$(ls -A ${{ env.BLAZIUM_TEMPLATE }})" ]; then
            echo "Template is empty"
            exit 1
          fi
      
